apiVersion: apps/v1
kind: Deployment
metadata:
  name: aemo-v5
  namespace: aemo-v5
  labels:
    app: aemo-v5
    version: v1.0.0
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: aemo-v5
  template:
    metadata:
      labels:
        app: aemo-v5
        version: v1.0.0
      annotations:
        argocd.argoproj.io/sync-wave: "0"
        timestamp: "1761186235"
        deployment.kubernetes.io/revision: "1"
    spec:
      containers:
      - name: aemo-v5
        image: ghcr.io/blueduck0907/aemo-v5:main-650e63dda55afabffad723435611f01a42402255
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
          name: http
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: aemo-v5-config
              key: FLASK_ENV
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: aemo-v5-config
              key: PYTHONUNBUFFERED
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: aemo-v5-config
              key: PORT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
