apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-v53
  namespace: demo-v53
  labels:
    app: demo-v53
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: demo-v53
  template:
    metadata:
      labels:
        app: demo-v53
        version: v1.0.0
      annotations:
        argocd.argoproj.io/sync-wave: "0"
        timestamp: "1760343782"
        deployment.kubernetes.io/revision: "1"
    spec:
      containers:
      - name: demo-v53
        image: ghcr.io/ductri09072004/demo-v53:main-9e03496e4cdb817fd0101a1f14cac04361c562f9
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
          name: http
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: demo-v53-config
              key: FLASK_ENV
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: demo-v53-config
              key: PYTHONUNBUFFERED
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
