apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: base-8-hpa
  namespace: base-8
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: base-8
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
