apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-v74
  namespace: demo-v74
  labels:
    app: demo-v74
    version: v1.0.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: demo-v74
  template:
    metadata:
      labels:
        app: demo-v74
        version: v1.0.0
      annotations:
        argocd.argoproj.io/sync-wave: "0"
        timestamp: "1760584541"
        deployment.kubernetes.io/revision: "1"
    spec:
      containers:
      - name: demo-v74
        image: ghcr.io/ductri09072004/demo-v74:main-d876a6edbbeafeb3694f67ce317b2c7fee8e0fd1
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
          name: http
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: demo-v74-config
              key: FLASK_ENV
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: demo-v74-config
              key: PYTHONUNBUFFERED
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: demo-v74-config
              key: PORT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5003
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
