apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - name: argocd-cm
          mountPath: /app/config/argocd-cm.yaml
          subPath: configManagementPlugins
      volumes:
      - name: argocd-cm
        configMap:
          name: argocd-cm
