apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  reposerver.configManagementPlugins: |
    - name: mongo-plugin
      generate:
        command: ["/bin/sh", "-c"]
        args:
          - >
            python cmp/generator.py
