apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-v21-hpa
  namespace: demo-v21
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-v21
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
