apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aka-75-hpa
  namespace: aka-75
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aka-75
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
