apiVersion: v1
kind: Service
metadata:
  name: demo-fiss-service
  namespace: demo-fiss
  labels:
    app: demo-fiss-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: demo-fiss-api
