apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-v56
  namespace: demo-v56
  labels:
    app: demo-v56
    version: v1.0.0
spec:
  replicas: {REPLICAS}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: demo-v56
  template:
    metadata:
      labels:
        app: demo-v56
        version: v1.0.0
      annotations:
        argocd.argoproj.io/sync-wave: "0"
        timestamp: "1760331233"
        deployment.kubernetes.io/revision: "1"
    spec:
      containers:
      - name: demo-v56
        image: ghcr.io/{GITHUB_USERNAME}/demo-v56:latest
        imagePullPolicy: Always
        ports:
        - containerPort: {PORT}
          name: http
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: demo-v56-config
              key: FLASK_ENV
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: demo-v56-config
              key: PYTHONUNBUFFERED
        resources:
          requests:
            memory: "{MEMORY_REQUEST}"
            cpu: "{CPU_REQUEST}"
          limits:
            memory: "{MEMORY_LIMIT}"
            cpu: "{CPU_LIMIT}"
        livenessProbe:
          httpGet:
            path: /api/health
            port: {PORT}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: {PORT}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
