apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: danjo-test-3-hpa
  namespace: danjo-test-3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: danjo-test-3
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
