apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: SERVICE_NAME
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ductri09072004/demo_fiss1_B
    targetRevision: HEAD
    path: cmp
    plugin:
      name: mongo-plugin
      env:
        - name: API_BASE
          value: https://auto-tool-production.up.railway.app
        - name: SERVICE_NAME
          value: SERVICE_NAME
  destination:
    server: https://kubernetes.default.svc
    namespace: SERVICE_NAME
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
