apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  configManagementPlugins: |
    - name: mongo-plugin
      generate:
        command: ["/bin/sh", "-c"]
        args:
          - >
            python cmp/generator.py

