apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-v61-hpa
  namespace: demo-v61
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-v61
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
