apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aemo-v6-hpa
  namespace: aemo-v6
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aemo-v6
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
