apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-v94
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://virtual-git-service.virtual-git.svc.cluster.local:8050
    targetRevision: HEAD
    path: api/git/demo-v94
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-v94
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
  revisionHistoryLimit: 3
