apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-v61
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ductri09072004/demo_fiss1_B
    targetRevision: HEAD
    path: services/demo-v61/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-v61
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
  revisionHistoryLimit: 3
