apiVersion: v1
kind: Service
metadata:
  name: node-v1-service
  namespace: node-v1
  labels:
    app: node-v1
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: node-v1
