apiVersion: v1
kind: Service
metadata:
  name: demo-v117-service
  namespace: demo-v117
  labels:
    app: demo-v117
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: demo-v117
