apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-v104
  namespace: demo-v104
  labels:
    app: demo-v104
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: demo-v104
  template:
    metadata:
      labels:
        app: demo-v104
        version: v1.0.0
      annotations:
        argocd.argoproj.io/sync-wave: "0"
        timestamp: "1760675868"
        deployment.kubernetes.io/revision: "1"
    spec:
      containers:
      - name: demo-v104
        image: ghcr.io/ductri09072004/demo-v104:main-5b045b074e6068d3919eaeaf664a9a41afb4f803
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
          name: http
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: demo-v104-config
              key: FLASK_ENV
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: demo-v104-config
              key: PYTHONUNBUFFERED
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: demo-v104-config
              key: PORT
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
